language: php
php:
  - 7.2.5
env:
  - SYMFONY_VERSION="5.0.*" DB=mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS easa;'
install:
  - composer install
before_script:
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load --force

script:
  - vendor/bin/phpunit


